packaging_format = 2

id = "statpingng"
name = "statping-ng"
description.en = "External monitoring tool"
description.fr = "Outils de monitoring externe"

version = "0.92.0~ynh1"

maintainers = ["oiseauroch"]

[upstream]
license = "GPL-3.0-only"
website = "https://statping-ng.github.io/"
admindoc = "https://github.com/statping-ng/statping-ng/wiki"
userdoc = "https://statping-ng.github.io/"
code = "https://github.com/statping-ng/statping-ng/"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "150M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr", "en", "es", "ru", "de", "cs", "ja", "ko", "it", "zh"]
    default = "fr"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    amd64.url = "https://github.com/statping-ng/statping-ng/releases/download/v0.92.0/statping-linux-amd64.tar.gz"
    amd64.sha256 = "71e9a965ad38e35468f5da78ef2caf93e3f735b3df4c75234de1faf542fba3be"
    arm64.url = "https://github.com/statping-ng/statping-ng/releases/download/v0.92.0/statping-linux-arm64.tar.gz"
    arm64.sha256 = "f877d9f79b922d01f87e733d57f7ded9aa9ddc3fd41c77f557ba48f2005c0489"
    i386.url = "https://github.com/statping-ng/statping-ng/releases/download/v0.92.0/statping-linux-386.tar.gz"
    i386.sha256 = "96180c5122962a76187f96f69c0441de48184989efcb73d924383b6e46df516f"
    armhf.url = "https://github.com/statping-ng/statping-ng/releases/download/v0.92.0/statping-linux-arm-7.tar.gz"
    armhf.sha256 = "9f14099159fff51b4aa70b3757c9d22ae8b2022f55d13786f436cd69600c5ac7"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^statping-linux-amd64.tar.gz$"
    autoupdate.asset.arm64 = "^statping-linux-arm64.tar.gz$"
    autoupdate.asset.i386 = "^statping-linux-386.tar.gz$"
    autoupdate.asset.armhf = "^statping-linux-arm-7.tar.gz$"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "postgresql"

    [resources.database]
    type = "postgresql"
