packaging_format = 2

id = "statpingng"
name = "statping-ng"
description.en = "External monitoring tool"
description.fr = "Outils de monitoring externe"

version = "0.93.0~ynh1"

maintainers = ["oiseauroch"]

[upstream]
license = "GPL-3.0-only"
website = "https://statping-ng.github.io/"
admindoc = "https://github.com/statping-ng/statping-ng/wiki"
userdoc = "https://statping-ng.github.io/"
code = "https://github.com/statping-ng/statping-ng/"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "150M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr", "en", "es", "ru", "de", "cs", "ja", "ko", "it", "zh"]
    default = "fr"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    amd64.url = "https://github.com/statping-ng/statping-ng/releases/download/v0.93.0/statping-linux-amd64.tar.gz"
    amd64.sha256 = "263ca172c19a61e7272618c5b4acdaab855580a5289963205c5160024628b82d"
    arm64.url = "https://github.com/statping-ng/statping-ng/releases/download/v0.93.0/statping-linux-arm64.tar.gz"
    arm64.sha256 = "ac116f81d78affb7b21f5b18789e70e79a4247f555314119a31fa90766431bc4"
    i386.url = "https://github.com/statping-ng/statping-ng/releases/download/v0.93.0/statping-linux-386.tar.gz"
    i386.sha256 = "bab0c99562973a71f3309056e5826d6fb266c3b6f2b215947c9f62e510d712d6"
    armhf.url = "https://github.com/statping-ng/statping-ng/releases/download/v0.93.0/statping-linux-arm-7.tar.gz"
    armhf.sha256 = "0b2bacb8db0203b487fb778268c3719f0f204a8ff3314a17635e5a138e3c4a02"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^statping-linux-amd64.tar.gz$"
    autoupdate.asset.arm64 = "^statping-linux-arm64.tar.gz$"
    autoupdate.asset.i386 = "^statping-linux-386.tar.gz$"
    autoupdate.asset.armhf = "^statping-linux-arm-7.tar.gz$"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "postgresql"

    [resources.database]
    type = "postgresql"
