#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#==================================================
# Change config file
#==================================================
ynh_script_progression "Modifying configuration file..."

#ynh_delete_file_checksum "$install_dir/.env"
#ynh_config_add --template=".env" --destination="$install_dir/.env"

sed -i "/DOMAIN=/c\DOMAIN=https://${new_domain}" $install_dir/.env

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
